express-notes-api - Marianne Cuevas
mariannecuevas/m2-0323-code-solutions pull request #31
Opened 2023-05-19 04:14 UTC by mariannecuevas

![Screenshot 2023-05-16 200749](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/c0206eae-ae69-4197-aa84-d2d81bd2f81b)
![Screenshot 2023-05-16 202220](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/f42409ec-e37b-492b-85cd-06f636938cad)
![Screenshot 2023-05-18 205117](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/fff62953-ed3f-4fa4-9417-59260abab660)
![Screenshot 2023-05-18 205242](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/ceaffdd9-f8e8-4e45-b82b-2c78e104dc64)
![Screenshot 2023-05-18 205340](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/14ef0007-afdd-42df-b7f1-13558509b541)
![Screenshot 2023-05-18 205523](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/b6cde79d-082d-450f-b19f-f276e12ac6e1)

2023-05-19 04:20 UTC, TimelikeClosure requested changes

2023-05-19 04:20 UTC, TimelikeClosure commented on express-notes-api/server.js
> +}
If a file read or write error occurs during a request, the server should respond with a `500 Internal Server Error`. Please add screenshots to your pull request to verify these responses are sent correctly.

2023-05-19 04:20 UTC, TimelikeClosure commented on express-notes-api/server.js
> +  }
Please improve your id validation to send `400 Bad Request` responses on positive non-integer numbers.

2023-05-19 04:20 UTC, TimelikeClosure commented on express-notes-api/server.js
> +      res.sendStatus(204);
Successful `PUT`s should result in the correct status code.

2023-05-22 00:49 UTC, mariannecuevas commented
![Screenshot 2023-05-21 173036](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/d5bd3438-77ba-4363-a930-b927ea45c686)
![Screenshot 2023-05-21 173754](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/037b7ca9-7c22-44d8-a5c7-cb86df60726e)
![Screenshot 2023-05-21 174039](https://github.com/mariannecuevas/m2-0323-code-solutions/assets/117552789/3a4f388b-6565-4b08-a5be-2d1df50f3e31)

I'm not quite sure if this is right.

2023-05-23 02:02 UTC, TimelikeClosure approved these changes

2023-05-23 02:18 UTC, merged